# Generated by Django 4.1.7 on 2023-03-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_drugs_owner_delete_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='availability',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable')], max_length=20),
        ),
    ]
