# Generated by Django 4.1.7 on 2023-03-21 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_drugs_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='api.drugcategories'),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='drug_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_class', to='api.drugclasses'),
        ),
    ]
